# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: check.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'check.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63heck.proto\"z\n\x0c\x43heckRequest\x12\x1e\n\nquery_type\x18\x01 \x01(\x0e\x32\n.QueryType\x12\x12\n\nposition_x\x18\x02 \x01(\x05\x12\x12\n\nposition_y\x18\x03 \x01(\x05\x12\x11\n\tquery_num\x18\x04 \x01(\x05\x12\x0f\n\x07\x65ncrypt\x18\x05 \x01(\x08\"J\n\x0b\x43heckResult\x12\x12\n\nposition_x\x18\x01 \x01(\x05\x12\x12\n\nposition_y\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x61tabase_id\x18\x03 \x01(\x05\".\n\rCheckResponse\x12\x1d\n\x07results\x18\x01 \x03(\x0b\x32\x0c.CheckResult\"\x1d\n\nAddRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"-\n\x0b\x41\x64\x64Response\x12\x1e\n\nadd_result\x18\x01 \x01(\x0e\x32\n.AddResult\"\x1a\n\x0bMapResponse\x12\x0b\n\x03map\x18\x01 \x01(\x0c*)\n\tQueryType\x12\x0b\n\x07Nearest\x10\x00\x12\x0f\n\x0b\x41ntiNearest\x10\x01*\"\n\tAddResult\x12\x08\n\x04\x46\x61il\x10\x00\x12\x0b\n\x07Success\x10\x01\x32\x91\x01\n\x10\x46\x65\x64\x65ratedService\x12&\n\x05\x43heck\x12\r.CheckRequest\x1a\x0e.CheckResponse\x12(\n\x0b\x41\x64\x64\x44\x61tabase\x12\x0b.AddRequest\x1a\x0c.AddResponse\x12+\n\x0bGenerateMap\x12\x0e.CheckResponse\x1a\x0c.MapResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'check_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYTYPE']._serialized_start=369
  _globals['_QUERYTYPE']._serialized_end=410
  _globals['_ADDRESULT']._serialized_start=412
  _globals['_ADDRESULT']._serialized_end=446
  _globals['_CHECKREQUEST']._serialized_start=15
  _globals['_CHECKREQUEST']._serialized_end=137
  _globals['_CHECKRESULT']._serialized_start=139
  _globals['_CHECKRESULT']._serialized_end=213
  _globals['_CHECKRESPONSE']._serialized_start=215
  _globals['_CHECKRESPONSE']._serialized_end=261
  _globals['_ADDREQUEST']._serialized_start=263
  _globals['_ADDREQUEST']._serialized_end=292
  _globals['_ADDRESPONSE']._serialized_start=294
  _globals['_ADDRESPONSE']._serialized_end=339
  _globals['_MAPRESPONSE']._serialized_start=341
  _globals['_MAPRESPONSE']._serialized_end=367
  _globals['_FEDERATEDSERVICE']._serialized_start=449
  _globals['_FEDERATEDSERVICE']._serialized_end=594
# @@protoc_insertion_point(module_scope)
