# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\"c\n\x0cQueryRequest\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.QueryType\x12\x12\n\nposition_x\x18\x02 \x01(\x05\x12\x12\n\nposition_y\x18\x03 \x01(\x05\x12\x11\n\tquery_num\x18\x04 \x01(\x05\"\x1d\n\tDisResult\x12\x10\n\x08\x64istance\x18\x05 \x01(\x02\"*\n\x0b\x44isResponse\x12\x1b\n\x07results\x18\x01 \x03(\x0b\x32\n.DisResult\"\x1e\n\nNumRequest\x12\x10\n\x08need_num\x18\x01 \x01(\x05\"J\n\x0bQueryResult\x12\x12\n\nposition_x\x18\x01 \x01(\x05\x12\x12\n\nposition_y\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x61tabase_id\x18\x03 \x01(\x05\".\n\rQueryResponse\x12\x1d\n\x07results\x18\x01 \x03(\x0b\x32\x0c.QueryResult*)\n\tQueryType\x12\x0b\n\x07Nearest\x10\x00\x12\x0f\n\x0b\x41ntiNearest\x10\x01\x32u\n\x18\x46\x65\x64\x65ratedDatabaseService\x12,\n\rQueryDistance\x12\r.QueryRequest\x1a\x0c.DisResponse\x12+\n\x0cQueryNeedNum\x12\x0b.NumRequest\x1a\x0e.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYTYPE']._serialized_start=347
  _globals['_QUERYTYPE']._serialized_end=388
  _globals['_QUERYREQUEST']._serialized_start=15
  _globals['_QUERYREQUEST']._serialized_end=114
  _globals['_DISRESULT']._serialized_start=116
  _globals['_DISRESULT']._serialized_end=145
  _globals['_DISRESPONSE']._serialized_start=147
  _globals['_DISRESPONSE']._serialized_end=189
  _globals['_NUMREQUEST']._serialized_start=191
  _globals['_NUMREQUEST']._serialized_end=221
  _globals['_QUERYRESULT']._serialized_start=223
  _globals['_QUERYRESULT']._serialized_end=297
  _globals['_QUERYRESPONSE']._serialized_start=299
  _globals['_QUERYRESPONSE']._serialized_end=345
  _globals['_FEDERATEDDATABASESERVICE']._serialized_start=390
  _globals['_FEDERATEDDATABASESERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
